# Database container for Application works on mysql
# Exposing port 80, create database, user and password
db:
  image: tayyab/db
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_DATABASE: test_db
    MYSQL_USER: test_user
    MYSQL_PASSWORD: test_pass
    MYSQL_ROOT_PASSWORD: sqladmin
  volumes:
    - /root/mysql/data_dir:/var/lib/mysql

# Tomcat Applciation conatiner hosting the JIRA application
# connects to database and exposes port 80 to load balancer
app:
   image: tayyab/app
   hostname: app
   links:
     - db
   ports:
     - "8080:8080"
   environment:
     NAME: "Tayyab Khan"

# Nginix Load balancer container
lb:
  image: tayyab/lb
  hostname: lb
  ports:
    - "80:80"
  links:
    - app